### ISSUE TITLE
help

### ISSUE THREAD

**Issue by meatieboyy** [mn-Devs/rick-roll#1]
Hey there! How tf do i get it off my computer?

**Comment by MauriceNorden** [comment]
Press windows key + r
Copy "%AppData%\Microsoft\Windows\Start Menu\Programs\Startup\" without the quoteation marks in there.
Search for the file "script.bat" in the folder and delete it.

Hope this solves your problem

**Comment by meatieboyy** [comment]
Thank u :) nearly got in trouble for that
